### ISSUE TITLE
Please allow an external double-conversion

### ISSUE THREAD

**Issue by pinotree** [davisp/jiffy#105]
Currently, jiffy embeds a copy of the double-conversion library. This causes a number of issues, for example #67, #82, #97, and #99.
Usually it is packaged, at least on Linux distributions, so it would be nice to have the possibility to build jiffy using an external double-conversion, which could allow to fix architecture issues in double-conversion just once.

**Comment by davisp** [comment]
Well, #82, #97, and #99 were only caused because I insist on using -Werror when compiling so that I get those reports rather than having something subtly maybe broken out in the wild. If memory serves the double conversion library doesn't build with that strict of a compiler setting so likely a system library would've never even noticed the issue. Speaking of which I should submit that PR to get it fixed upstream.

That said if you want to make it possible to disable using the bundled double-conversion code I'd review any PRs. But given that I have to maintain the bundled version anyway I'm not going to elect to do it on my own.

**Comment by davisp** [comment]
Whoops. I guess I already did submit that upstream. PR is still open though:

https://github.com/google/double-conversion/pull/15

**Comment by pinotree** [comment]
> Well, #82, #97, and #99 were only caused because I insist on using -Werror when compiling so that I get those reports rather than having something subtly maybe broken out in the wild.

That's good, sure, but you are effectively redoing the maintenance job done already by double-conversion upstream. #67 shows exactly why: the upstream project gets fixes, but the bundled copies in other projects don't get updated and force people to resubmit fixes.

> But given that I have to maintain the bundled version anyway I'm not going to elect to do it on my own.

Then just get rid of the bundled version in favour of the external version only -- less maintenance burden at all on your side.
