### ISSUE TITLE
Return decode keys as list/string

### ISSUE THREAD

**Issue by nOmi7** [davisp/jiffy#134]
Hello
 Currently keys are returned as binary can that be retruned as list / string 

current
 jiffy:decode(<<"{\"t\":\"TPO\",\"token\":\"d890\",\"token_type\":2}">>).   
  {[{_<<"t">>_,<<"TPO">>},{_<<"token">>_,<<"d890">>}, {_<<"token_type">>_,2}]}

can this happen to 
  {[{**"t"**,<<"TPO">>},{**"token"**,<<"d890">>}, {**"token_type"**,2}]}

Thanks

**Comment by lpgauth** [comment]
Lists are less efficient, you can always use `binary_to_list/1`.

**Comment by nOmi7** [comment]
This is what we are doing after i get response from jiffy I am changing it list howerver is there any way that jiffy would return it instead me adding extra overhead?

**Comment by davisp** [comment]
The overhead is going to be there regardless of whether you're writing it in C or in Erlang and given that Erlang is going to be a lot easier to maintain I'd write it there. And its always been my policy to not include options for everyone's favorite JSON representation in Erlang.

If you want to have a custom format like this my suggestion has always been to just write a function that you call instead of jiffy that does the conversion each time (rather than call Jiffy and then call your conversion). And if you just create a small library app you can just depend on it in your own projects and automatically pull Jiffy if you re-use it between projects.

**Comment by nOmi7** [comment]
@davisp thanks for the info i understand there would be overhead in both erlang and c but i thought there would be some func like erl_get_string or make_string which can be used for the same and woild be faster than erlang overhead as its custom code if you can help me or guide me with this change i can make it in my project and try I would be really thank full if you can help me with the same also this only for decoder and not encoder.
