### ISSUE TITLE
exception throw: {error,{56,invalid_string}}

### ISSUE THREAD

**Issue by nestor5** [davisp/jiffy#145]
Decoding this string failed:

> jiffy:decode(<<"{\"a\": \"\\u270a\\u270a\\u270a\\ud83d\\udc4a\\ud83d\\udc4a\\ud83d\"}">>).
** exception throw: {error,{56,invalid_string}}

But it can be decoded by python and node.js:

Python:
>>> import json
>>> json.loads("{\"a\": \"\\u270a\\u270a\\u270a\\ud83d\\udc4a\\ud83d\\udc4a\\ud83d\"}")
{u'a': u'\u270a\u270a\u270a\U0001f44a\U0001f44a\ud83d'}

Node.js:
> JSON.parse("{\"a\": \"\\u270a\\u270a\\u270a\\ud83d\\udc4a\\ud83d\\udc4a\\ud83d\"}")
{ a: '✊✊✊�' }

If the last unicode is removed from the string, the it can be decoded by jiffy

> jiffy:decode(<<"{\"a\": \"\\u270a\\u270a\\u270a\\ud83d\\udc4a\\ud83d\\udc4a\"}">>).
{[{<<"a">>,
   <<226,156,138,226,156,138,226,156,138,240,159,145,138,
     240,159,145,138>>}]}

Why?  Because the last emoji is incomplete?

\\u270a\\u270a\\u270a\\ud83d\\udc4a\\ud83d\\udc4a is actually ✊✊✊👊👊.

**Comment by davisp** [comment]
Correct. Having half of a surrogate pair like that is invalid UTF-8 and Jiffy was written for use in a database so its extremely conservative in what it accepts rather than either trying to maintain invalid UTF-8 throughout or allowing for the possibility of subtle data mutation between what a user intended to store and what actually got stored and/or returned.
