### ISSUE TITLE
Decode Unicode string error

### ISSUE THREAD

**Issue by barcoyou** [davisp/jiffy#196]
>jiffy:decode(<<"{\"time\":\"2020-4-13 23:59:11\",\"Data\":[{\"name\":\"I0.0\",\"value\":\"0\"},{\"name\":\"Q0.1\",\"value\":\"0\"},{\"name\":\"Q0.0\",\"value\":\"0\"},{\"name\":\"趋势\",\"value\":\"1\"},{\"name\":\"mqtt\",\"value\":\"1\"}]}">>).
** exception error: {131,invalid_string}
     in function  jiffy:decode/2 (src/jiffy.erl, line 71)

**Comment by davisp** [comment]
Howdy,

I totally missed this. If you're still having issues (checks date....) almost two years later, could you paste me the data you were attempting to decode. You'll want to convert to hex or base64 so that we can make sure and get all of the underlying UTF-8 values without various intermediaries messing them up with replacement values.
